name = "Geran-4"
prefix = "db_geran4"
mainprefix = "z"
author = "DarkBall, Sam, and contributors"

[files]
include = [
    "meta.cpp",
    "mod.cpp",
    "mod.paa",
    "mod_small.paa",
    "preview.jpg",
]

exclude = [
    "**/.DS_Store",
    "**/Thumbs.db",
    "**/*.bak",
    "**/*.bak.*",
    "**/*.back.*",
    "**/*.tmp",
    "**/*.orig",
    "**/*.rej",
    "**/* - Copy.*",
    "**/*.psd",
    "**/*.psb",
    "**/*.xcf",
    "**/*.blend",
    "**/*.blend1",
    "**/.gitkeep",
    "addons/**/README*",
    "optionals/**/README*",
]

[version]
major = 1
minor = 0
patch = 0
git_hash = 0

[hemtt.build]
pdrive = "disallow"

[hemtt.release]
folder = "Geran_4"

[signing]
authority = "db_geran4"
